###################
#RPG Bukkit Config#
###################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 2

###########
#Inventory#
###########

#Inventory Title Prefix (REQUIRED)
InventoryPrefix: yellow,bold


############
#Experience#
############

#Display XP on BossBar?
BossBar: true

#BossBar Prefix
BossBarPrefix: red,bold

#BossBar Style (SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12 or SEGMENTED_20)
BossBarStyle: SEGMENTED_20

#Delay before boss bar disappears
BossBarDelay: 200

#XP Definitions in xp.yml File