name: PseudoPlaceholders
author: PseudoResonance
main: io.github.pseudoresonance.pseudoplaceholders.PseudoPlaceholders
version: 1.0.1
description: Placeholder hooks for PseudoResonance's plugins
api-version: 1.13
depend: [PseudoAPI]
softdepend: [PlaceholderAPI]
commands:
  pseudoplaceholders:
    description: PseudoPlaceholders Menu
permissions:
  pseudoplaceholders.reload:
    description: Allows the player to reload the placeholder hooks
    default: op
  pseudoplaceholders.*:
    description: Gives the user all PseudoPlaceholders permissions
    default: op
    children:
      pseudoplaceholders.reload: true