name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoplaceholders.PseudoPlaceholders
version: ${revision}
description: Placeholder hooks for PseudoResonance's plugins
api-version: 1.13
depend: [PseudoAPI]
softdepend: [PlaceholderAPI,PseudoMusic,PseudoPlayers,PseudoUtils]
commands:
  pseudoplaceholders:
    description: PseudoPlaceholders Menu
permissions:
  pseudoplaceholders.reload:
    description: Allows the player to reload the placeholder hooks
    default: op
  pseudoplaceholders.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudoplaceholders.resetlocalization:
    description: Allows the player to reload the localization
    default: op
    children:
      pseudoplaceholders.reloadlocalization: true
  pseudoplaceholders.*:
    description: Gives the user all PseudoPlaceholders permissions
    default: op
    children:
      pseudoplaceholders.reload: true
      pseudoplaceholders.resetlocalization: true